# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: oracle_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'oracle_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import indexing_server_pb2 as indexing__server__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14oracle_service.proto\x12\x12\x62lindbit.oracle.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15indexing_server.proto2\xcc\x07\n\rOracleService\x12j\n\x14StreamBlockBatchSlim\x12,.blindbit.oracle.v1.RangedBlockHeightRequest\x1a\".blindbit.oracle.v1.BlockBatchSlim0\x01\x12j\n\x14StreamBlockBatchFull\x12,.blindbit.oracle.v1.RangedBlockHeightRequest\x1a\".blindbit.oracle.v1.BlockBatchFull0\x01\x12W\n\rGetTweakArray\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a\x1e.blindbit.oracle.v1.TweakArray\x12^\n\x12GetTweakIndexArray\x12(.blindbit.oracle.v1.GetTweakIndexRequest\x1a\x1e.blindbit.oracle.v1.TweakArray\x12]\n\x0cGetUTXOArray\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a%.blindbit.oracle.v1.UTXOArrayResponse\x12U\n\tGetFilter\x12$.blindbit.oracle.v1.GetFilterRequest\x1a\".blindbit.oracle.v1.FilterRepsonse\x12q\n\x16GetSpentOutpointsIndex\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a/.blindbit.oracle.v1.SpentOutpointsIndexResponse\x12\x43\n\x07GetInfo\x12\x16.google.protobuf.Empty\x1a .blindbit.oracle.v1.InfoResponse\x12U\n\x12GetBestBlockHeight\x12\x16.google.protobuf.Empty\x1a\'.blindbit.oracle.v1.BlockHeightResponse\x12\x65\n\x14GetBlockHashByHeight\x12&.blindbit.oracle.v1.BlockHeightRequest\x1a%.blindbit.oracle.v1.BlockHashResponseB\x06Z\x04./pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'oracle_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./pb'
  _globals['_ORACLESERVICE']._serialized_start=97
  _globals['_ORACLESERVICE']._serialized_end=1069
# @@protoc_insertion_point(module_scope)
